# ==============================================================================
# QUARKUS JSSHT CONFIGURATION (2026 Native Ready)
# ==============================================================================
quarkus:
  
  # Wolfetti's banner
  banner:
    path: banner.txt
    enabled: true

  # Log Management
  log:
    level: ${LOG_LEVEL_LIB:ERROR}
    category:
      "org.github.wolfetti":
        min-level: TRACE
        level: ${LOG_LEVEL_APP:INFO}
      "com.jcraft.jsch":
        level: ${LOG_LEVEL_LIB:ERROR}

  # External configuration file loading (MULTI_TUNNEL_CONF_PATH)
  config:
    locations: "${MULTI_TUNNEL_CONF_PATH:application.yaml}"
  
  # Native build management
  native:
    
   # Register required JSch packages for reflection in native mode
   reflective-hierarchy:
     packages:
       - com.jcraft.jsch
       - com.jcraft.jsch.jce
       - com.jcraft.jsch.jcraft

# ==============================================================================
# SSH PARAMETERS
# ==============================================================================
ssh:
  host: ${SSH_HOST}
  user: ${SSH_USER}
  private-key: ${SSH_PRIVATE_KEY:private.key}

# ==============================================================================
# SINGLE TUNNEL CONFIGURATION (Active if multi-tunnel.enabled: false)
# ==============================================================================
tunnel:
  host: ${TUNNEL_HOST}
  port: ${TUNNEL_PORT}

# ==============================================================================
# MULTI TUNNEL CONFIGURATION (Active if multi-tunnel.enabled: true)
# ==============================================================================
multi-tunnel:
  enabled: ${MULTI_TUNNEL_ENABLED:false}
