# ==============================================================================
# CONFIGURAZIONE QUARKUS JSSHT (2026 Native Ready)
# ==============================================================================
quarkus:
  banner:
    path: banner.txt
    enabled: true

  # Gestione dei log
  log:
    level: ${LOG_LEVEL_LIB:ERROR}
    category:
      "org.github.wolfetti":
        min-level: TRACE
        level: ${LOG_LEVEL_APP:INFO}
      "com.jcraft.jsch":
        level: ${LOG_LEVEL_LIB:ERROR}

  # Retrocompatibilit√† per il caricamento del file esterno (MULTI_TUNNEL_CONF_PATH)
  config:
    locations: "${MULTI_TUNNEL_CONF_PATH:application.yaml}"

# ==============================================================================
# PARAMETRI SSH
# ==============================================================================
ssh:
  host: ${SSH_HOST}
  user: ${SSH_USER}
  private-key: ${SSH_PRIVATE_KEY:private.key}

# ==============================================================================
# CONFIGURAZIONE SINGLE TUNNEL (Attiva se multi-tunnel.enabled: false)
# ==============================================================================
tunnel:
  host: ${TUNNEL_HOST}
  port: ${TUNNEL_PORT}

# ==============================================================================
# CONFIGURAZIONE MULTI TUNNEL (Attiva se multi-tunnel.enabled: true)
# ==============================================================================
multi-tunnel:
  enabled: ${MULTI_TUNNEL_ENABLED:false}

